# -*- coding: utf-8 -*-
"""task 2 complete

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VlNdim4BoZl1OX67aB0e_rlOq5xa8BuC
"""

!pip install diffusers transformers accelerate scipy safetensors

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to("cuda")

from huggingface_hub import login
login()

prompt = "birds are flying"
image = pipe(prompt).images[0]

display(image)

import torch
print("CUDA Available:", torch.cuda.is_available())

"""# **complete code**

---


"""

!pip install diffusers transformers accelerate scipy safetensors

from diffusers import StableDiffusionPipeline
import torch
from IPython.display import display

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to("cuda")

prompt = "a sunrise near ocean"
image = pipe(prompt).images[0]
display(image)

# Optional: Save and download
image.save("my_image.png")
from google.colab import files
files.download("my_image.png")